import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { getDashboard } from '../api'

function StatCard({ label, value, sub }) {
  return (
    <div className="bg-slate-800 rounded-xl p-5 border border-slate-700">
      <p className="text-slate-400 text-sm">{label}</p>
      <p className="text-3xl font-bold text-white mt-1">{value ?? '—'}</p>
      {sub && <p className="text-slate-500 text-xs mt-1">{sub}</p>}
    </div>
  )
}

function MatchRow({ match, isResult }) {
  return (
    <Link
      to={`/match/${match.id}`}
      className="flex items-center justify-between px-4 py-3 rounded-lg hover:bg-slate-700 transition-colors"
    >
      <span className="text-slate-300 text-sm w-36 truncate">{match.home_team}</span>
      <span className="text-white font-bold text-sm mx-2">
        {isResult
          ? `${match.home_goals} - ${match.away_goals}`
          : 'vs'
        }
      </span>
      <span className="text-slate-300 text-sm w-36 truncate text-right">{match.away_team}</span>
      <span className="text-slate-500 text-xs ml-4 w-20 text-right">
        {new Date(match.match_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}
      </span>
    </Link>
  )
}

export default function Dashboard() {
  const { data, isLoading, error } = useQuery({
    queryKey: ['dashboard'],
    queryFn: getDashboard,
  })

  if (isLoading) return <div className="text-slate-400 text-center py-20">Loading dashboard...</div>
  if (error) return <div className="text-red-400 text-center py-20">Failed to load dashboard.</div>

  return (
    <div className="space-y-8">
      <h1 className="text-2xl font-bold text-white">Dashboard</h1>

      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <StatCard
          label="Prediction Accuracy"
          value={data.accuracy ? `${data.accuracy}%` : 'N/A'}
          sub={`${data.evaluated_predictions} predictions evaluated`}
        />
        <StatCard
          label="Total Predictions"
          value={data.total_predictions}
          sub="Generated by model"
        />
        <StatCard
          label="Season"
          value="2024/25"
          sub="EPL · Poisson DC Model"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-slate-800 rounded-xl border border-slate-700 p-5">
          <h2 className="text-slate-300 font-semibold mb-4">Recent Results</h2>
          {data.recent_results?.length > 0
            ? data.recent_results.map(m => <MatchRow key={m.id} match={m} isResult={true} />)
            : <p className="text-slate-500 text-sm">No recent results.</p>
          }
        </div>

        <div className="bg-slate-800 rounded-xl border border-slate-700 p-5">
          <h2 className="text-slate-300 font-semibold mb-4">Upcoming Fixtures</h2>
          {data.upcoming_fixtures?.length > 0
            ? data.upcoming_fixtures.map(m => <MatchRow key={m.id} match={m} isResult={false} />)
            : <p className="text-slate-500 text-sm">No upcoming fixtures in database. All 2024 season matches are complete.</p>
          }
        </div>
      </div>
    </div>
  )
}